use crate::config::RouterConfig;
use http_body_util::combinators::BoxBody;
use http_body_util::{BodyExt, Full};
use hyper::body::Bytes;
use hyper::server::conn::http1;
use hyper::service::service_fn;
use hyper::{Request, Response, StatusCode};
use hyper_util::rt::TokioIo;
use std::convert::Infallible;
use std::io;
use std::path::{Path, PathBuf};
use std::process::Stdio;

mod assets;
mod icons;
mod launch;
mod logs;
use self::icons::project_icons;
mod api;
mod http;
use self::http::serve_index;
mod discovery;
pub use self::api::load_runtime_config;
use self::discovery::{
    container_labels, discover_compose_containers_filtered_scoped, discover_fog_instances,
    project_name_from_common_dir,
};

// One embedded SPA file plus its precompressed variants (generated by
// `build.rs` at compile time, so serving them costs no runtime CPU).
// `embedded_get` returns this; see the generated module below.
// Fields are private: only this module constructs it, callers just pass it to
// the server internals.
pub struct EmbeddedAsset {
    /// Raw file bytes (identity encoding fallback).
    data: &'static [u8],
    /// Content-Type derived from the real asset filename.
    mime: &'static str,
    /// gzip bytes, when compressing shrank the file.
    gzip: Option<&'static [u8]>,
    /// brotli bytes, when compressing shrank the file.
    br: Option<&'static [u8]>,
}

// Embeds the frontend SPA build (`ui/dist/`), generated by `build.rs`. When the
// frontend has not been built yet this expands to an empty `embedded_get`
// returning `None`, so the crate still compiles.
include!(concat!(env!("OUT_DIR"), "/fog_embedded.rs"));

/// Default port for the embedded service-directory index server.
const DEFAULT_INDEX_PORT: u16 = 18080;

static CURRENT_INDEX_PORT: std::sync::atomic::AtomicU16 = std::sync::atomic::AtomicU16::new(0);

/// Default number of trailing lines served by the live-log stream.
const DEFAULT_LOG_TAIL: usize = 200;
/// Upper bound for the `tail` query parameter, so a single request cannot
/// request an unbounded backfill.
const MAX_LOG_TAIL: usize = 10_000;

/// HTTP response body used by the embedded server. Static pages and the SSE
/// log stream both box into this type so a single service fn serves them all.
type RespBody = BoxBody<Bytes, Infallible>;

/// One reachable service discovered from docker (Traefik labels or
/// `fog.expose` custom labels).
#[derive(Clone)]
struct IndexEntry {
    /// Display project name (e.g. `gems`, `red-fox`), derived from the repo
    /// root of the compose project's working dir.
    project: String,
    /// Worktree/branch group (e.g. `main`, `feature-x`). Shared infra services
    /// report `shared`.
    worktree: String,
    #[allow(dead_code)]
    /// Whether this is a shared infra service (under the `shared` subgroup).
    shared: bool,
    /// Docker container name (e.g. `redfox-main-api-1`), used to stream that
    /// container's logs.
    container: String,
    /// Compose service name (e.g. `frontend`, `postgres`).
    service: String,
    /// Hostname the router accepts (e.g. `main.red-fox`, `main.postgres.gems`).
    hostname: String,
    /// Internal container port Traefik forwards to. Empty for raw-TCP
    /// services exposed via `fog.expose` (they are reached by host port).
    port: String,
    /// Host-published docker port bindings of the container (e.g.
    /// `0.0.0.0:8080->8080/tcp`). Empty when nothing is published to the host.
    published: Vec<String>,
    /// The host port number docker published for this service, if any
    /// (e.g. `53012` for `0.0.0.0:53012->5173/tcp`).
    raw_port: Option<String>,
    /// Whether the router terminates TLS (`https`) or not (`http`).
    tls: bool,
}

/// Ensures the standalone index server is running. Idempotent and best-effort.
pub fn ensure(cfg: &RouterConfig) -> Vec<String> {
    ensure_with_router(cfg)
}

/// Ensures the index server for a full `Config`, respecting `index.enabled`
/// (default `true`) in both fog config (`~/.config/fog/fog.json` with `theme`)
/// and per-project `fog.json`. Either can opt-out. When disabled, no server
/// is started.
pub fn ensure_for_config(cfg: &crate::config::Config) -> Vec<String> {
    if !cfg.effective_should_serve_index() {
        return Vec::new();
    }
    let port = cfg.effective_index_port();
    let network = cfg.index_network();
    ensure_with_port(port, &network)
}

fn ensure_with_router(cfg: &RouterConfig) -> Vec<String> {
    let mut messages = Vec::new();
    if !command_exists("docker") {
        return messages;
    }
    let port = cfg.index_port.unwrap_or(DEFAULT_INDEX_PORT);
    if server_started(port) {
        return messages;
    }
    match spawn_server(cfg) {
        Ok(()) => messages.push(format!(
            "  + service index server on http://127.0.0.1:{port}"
        )),
        Err(e) => messages.push(format!("⚠ could not start index server on :{port} ({e})")),
    }
    messages
}

pub fn ensure_with_port(port: u16, network: &str) -> Vec<String> {
    let mut messages = Vec::new();
    if !command_exists("docker") {
        return messages;
    }
    if server_started(port) {
        return messages;
    }
    // Build a minimal RouterConfig for spawn_server.
    let cfg = RouterConfig {
        index_port: Some(port),
        shared_network: network.to_string(),
        ..Default::default()
    };
    match spawn_server(&cfg) {
        Ok(()) => messages.push(format!(
            "  + service index server on http://127.0.0.1:{port}"
        )),
        Err(e) => messages.push(format!("⚠ could not start index server on :{port} ({e})")),
    }
    messages
}

/// Whether the standalone index server is already listening.
fn server_started(port: u16) -> bool {
    std::net::TcpStream::connect(("127.0.0.1", port)).is_ok()
}

/// Public check whether the index server is listening on `port`.
pub fn is_server_started(port: u16) -> bool {
    server_started(port)
}

/// Path to the pidfile for the index server on `port`.
fn index_pid_path(port: u16) -> PathBuf {
    std::env::temp_dir().join(format!("fog-index-{port}.pid"))
}

/// Best-effort: terminate the index server on `port` if it is running.
///
/// Returns `true` if the server was stopped (or was not running).
fn terminate_server_on_port(port: u16) -> bool {
    // Prefer the pidfile, but fall back to a port probe.
    let pid: Option<u32> = std::fs::read_to_string(index_pid_path(port))
        .ok()
        .and_then(|s| s.trim().parse().ok());

    if let Some(pid) = pid {
        // If the pid is our own, don't signal ourselves — just clean up.
        if pid != std::process::id() && crate::process::is_pid_alive(pid) {
            let _ = crate::process::kill_process(pid, crate::process::Signal::Term);
            crate::process::try_kill_process_group(pid, crate::process::Signal::Term);
            // Give it a moment to exit gracefully.
            for _ in 0..20 {
                if !crate::process::is_pid_alive(pid) || !server_started(port) {
                    break;
                }
                std::thread::sleep(std::time::Duration::from_millis(100));
            }
            if crate::process::is_pid_alive(pid) && server_started(port) {
                let _ = crate::process::kill_process(pid, crate::process::Signal::Kill);
                crate::process::try_kill_process_group(pid, crate::process::Signal::Kill);
                std::thread::sleep(std::time::Duration::from_millis(200));
            }
        }
        let _ = std::fs::remove_file(index_pid_path(port));
        // Even if the pid was stale, consider it handled if the port is now closed.
        // For self-pid, the port is still open until we exit, so return true
        // to indicate the pidfile was handled; the caller will exit separately.
        if pid == std::process::id() {
            return true;
        }
        return !server_started(port);
    }

    // No pidfile: if nothing is listening we are already done.
    if !server_started(port) {
        return true;
    }

    // Fallback: try to discover the pid via lsof/fuser when no pidfile exists
    // (e.g. legacy server started before pidfile logic).
    if let Ok(out) = std::process::Command::new("lsof")
        .args(["-ti", &format!(":{}", port)])
        .output()
    {
        let pids = String::from_utf8_lossy(&out.stdout);
        for pid_str in pids.split_whitespace() {
            if let Ok(pid) = pid_str.parse::<u32>()
                && pid != std::process::id()
                && crate::process::is_pid_alive(pid)
            {
                // Try both process-group and direct kill for compatibility
                // with servers started with and without setsid.
                let _ = crate::process::kill_process(pid, crate::process::Signal::Term);
                crate::process::try_kill_process_group(pid, crate::process::Signal::Term);
                std::thread::sleep(std::time::Duration::from_millis(300));
                if crate::process::is_pid_alive(pid) {
                    let _ = crate::process::kill_process(pid, crate::process::Signal::Kill);
                    crate::process::try_kill_process_group(pid, crate::process::Signal::Kill);
                }
            }
        }
        std::thread::sleep(std::time::Duration::from_millis(300));
        return !server_started(port);
    }

    // Last resort: try to find `fog index serve` via `ps` is fragile; just
    // report failure and let the caller retry via polling self-exit.
    false
}

/// Kill the index server on `port` if no fog instances remain.
pub fn maybe_terminate_on_port(port: u16) {
    let instances = crate::ipc::find_instances().unwrap_or_default();
    let any_alive = instances
        .iter()
        .any(|(_, p)| crate::ipc::query_status(p).is_ok());
    if any_alive {
        return;
    }
    let _ = terminate_server_on_port(port);
    if port != DEFAULT_INDEX_PORT {
        let _ = terminate_server_on_port(DEFAULT_INDEX_PORT);
    }
}

/// Kill the index server for a full `Config` if no instances remain.
pub fn maybe_terminate_for_config(cfg: &crate::config::Config) {
    maybe_terminate_on_port(cfg.index_port());
}

/// Kill the index server if no fog instances remain.
///
/// Looks at `crate::ipc::find_instances()`. If no instances are alive,
/// attempts to stop the server on the configured port (or the default
/// `18080`). Best-effort and never panics.
pub fn maybe_terminate_if_no_instances(cfg: Option<&RouterConfig>) {
    let instances = crate::ipc::find_instances().unwrap_or_default();
    let any_alive = instances
        .iter()
        .any(|(_, p)| crate::ipc::query_status(p).is_ok());
    if any_alive {
        return;
    }
    // No live instance responded — idle, tear down the server.
    if let Some(c) = cfg {
        let port = c.index_port.unwrap_or(DEFAULT_INDEX_PORT);
        let _ = terminate_server_on_port(port);
        if port != DEFAULT_INDEX_PORT {
            let _ = terminate_server_on_port(DEFAULT_INDEX_PORT);
        }
        return;
    }
    // No config given (e.g. `fog kill` without a config): try the default
    // port and any pidfile-discovered custom ports.
    let _ = terminate_server_on_port(DEFAULT_INDEX_PORT);
    if let Ok(dir) = std::fs::read_dir(std::env::temp_dir()) {
        for entry in dir.flatten() {
            let name = entry.file_name().to_string_lossy().into_owned();
            if let Some(port_str) = name
                .strip_prefix("fog-index-")
                .and_then(|s| s.strip_suffix(".pid"))
                && let Ok(port) = port_str.parse::<u16>()
                && port != DEFAULT_INDEX_PORT
            {
                let _ = terminate_server_on_port(port);
            }
        }
    }
}

/// Kill the index server for a full `Config` (respects `index.port` then
/// `router.index_port`, plus global fog config fallback).
pub fn kill_for_config(cfg: &crate::config::Config) -> bool {
    let port = cfg.effective_index_port();
    let was_running = server_started(port);
    let _ = terminate_server_on_port(port);
    if port != DEFAULT_INDEX_PORT {
        let _ = terminate_server_on_port(DEFAULT_INDEX_PORT);
    }
    was_running && !server_started(port)
}

/// Restart the index server for a full `Config`.
pub fn restart_for_config(cfg: &crate::config::Config) -> Result<u16, String> {
    let _ = kill_for_config(cfg);
    std::thread::sleep(std::time::Duration::from_millis(300));
    ensure_for_config(cfg);
    let port = cfg.effective_index_port();
    if server_started(port) {
        return Ok(port);
    }
    Err(format!("server did not start on :{port}"))
}

/// Unconditionally kill the index server on `port` (or default when `cfg` is
/// `None`). Returns `true` if a server was running and is now stopped.
pub fn kill_server(cfg: Option<&RouterConfig>) -> bool {
    if let Some(c) = cfg {
        let port = c.index_port.unwrap_or(DEFAULT_INDEX_PORT);
        let was_running = server_started(port);
        let _ = terminate_server_on_port(port);
        if port != DEFAULT_INDEX_PORT {
            let _ = terminate_server_on_port(DEFAULT_INDEX_PORT);
        }
        return was_running && !server_started(port);
    }
    let was_running = server_started(DEFAULT_INDEX_PORT);
    let _ = terminate_server_on_port(DEFAULT_INDEX_PORT);
    // Also kill any custom-port servers discovered via pidfiles.
    if let Ok(dir) = std::fs::read_dir(std::env::temp_dir()) {
        for entry in dir.flatten() {
            let name = entry.file_name().to_string_lossy().into_owned();
            if let Some(port_str) = name
                .strip_prefix("fog-index-")
                .and_then(|s| s.strip_suffix(".pid"))
                && let Ok(port) = port_str.parse::<u16>()
                && port != DEFAULT_INDEX_PORT
            {
                let _ = terminate_server_on_port(port);
            }
        }
    }
    was_running && !server_started(DEFAULT_INDEX_PORT)
}

/// Kill then re-ensure the index server, returning the port it now serves on.
pub fn restart_server(cfg: Option<&RouterConfig>) -> Result<u16, String> {
    let _ = kill_server(cfg);
    // Give the OS a moment to release the port.
    std::thread::sleep(std::time::Duration::from_millis(300));
    if let Some(c) = cfg {
        ensure(c);
        let port = c.index_port.unwrap_or(DEFAULT_INDEX_PORT);
        if server_started(port) {
            return Ok(port);
        }
        // Fallback: ensure with a minimal config on the default port.
        let fallback = RouterConfig {
            shared_network: c.shared_network.clone(),
            ..Default::default()
        };
        ensure(&fallback);
        let port = fallback.index_port.unwrap_or(DEFAULT_INDEX_PORT);
        if server_started(port) {
            return Ok(port);
        }
        return Err(format!("server did not start on :{port}"));
    }
    // No config: start with defaults on 18080.
    let fallback = RouterConfig::default();
    ensure(&fallback);
    let port = fallback.index_port.unwrap_or(DEFAULT_INDEX_PORT);
    if server_started(port) {
        Ok(port)
    } else {
        Err(format!("server did not start on :{port}"))
    }
}

/// Directory holding a background index server's captured output:
/// `$TMPDIR/fog-index-<port>.logs/`. The detached server's own diagnostics
/// go to `daemon.log` inside it.
pub fn index_log_dir(port: u16) -> PathBuf {
    std::env::temp_dir().join(format!("fog-index-{port}.logs"))
}

/// Restricts `path` to owner-only permissions (`mode`) on Unix; no-op
/// elsewhere. Mirrors [`crate::ipc::ensure_instance_dir`], so an index log in
/// the shared temp dir is not readable by other local users.
#[cfg(unix)]
fn restrict_permissions(path: &Path, mode: u32) {
    use std::os::unix::fs::PermissionsExt;
    if let Ok(meta) = std::fs::metadata(path) {
        let mut perms = meta.permissions();
        perms.set_mode(mode);
        let _ = std::fs::set_permissions(path, perms);
    }
}

/// Restricts `path` to owner-only permissions (`mode`) on Unix; no-op
/// elsewhere.
#[cfg(not(unix))]
fn restrict_permissions(_path: &Path, _mode: u32) {}

/// Resolves the port for `fog index serve`: explicit `--port` wins, then
/// `FOG_INDEX_PORT`, then the effective config port (project/global fallback),
/// then the default.
pub fn resolve_serve_port(explicit: Option<u16>) -> u16 {
    if let Some(p) = explicit {
        return p;
    }
    if let Ok(p) = std::env::var("FOG_INDEX_PORT")
        && let Ok(p) = p.parse::<u16>()
    {
        return p;
    }
    load_runtime_config().effective_index_port()
}

/// Resolves the docker network for `fog index serve`: `FOG_INDEX_NETWORK`
/// wins, then the runtime config.
pub fn resolve_serve_network() -> String {
    std::env::var("FOG_INDEX_NETWORK")
        .ok()
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| load_runtime_config().index_network())
}

/// Launches the index server as a detached background process (`fog index
/// serve --foreground` as the child), so it survives the launching shell.
/// The child's stdout/stderr go to `daemon.log` in [`index_log_dir`].
/// If it is already running this is a no-op reporting the existing server.
pub fn serve_detached(port: u16, network: &str) -> io::Result<()> {
    if server_started(port) {
        println!("index server already running on :{port}");
        println!("  status: curl http://127.0.0.1:{port}/api/services");
        return Ok(());
    }
    let log_dir = index_log_dir(port);
    std::fs::create_dir_all(&log_dir).map_err(|e| {
        io::Error::other(format!(
            "could not create index log dir {}: {e}",
            log_dir.display()
        ))
    })?;
    restrict_permissions(&log_dir, 0o700);
    let log_file = std::fs::File::create(log_dir.join("daemon.log")).map_err(|e| {
        io::Error::other(format!(
            "could not create {}: {e}",
            log_dir.join("daemon.log").display()
        ))
    })?;
    restrict_permissions(&log_dir.join("daemon.log"), 0o600);
    // Separate fds for stdout/stderr so both capture the child's diagnostics.
    let log_err = log_file
        .try_clone()
        .map_err(|e| io::Error::other(format!("could not duplicate index log fd: {e}")))?;
    let exe = std::env::current_exe().unwrap_or_else(|_| PathBuf::from("fog"));
    let mut cmd = std::process::Command::new(&exe);
    cmd.args([
        "index",
        "serve",
        "--foreground",
        "--port",
        &port.to_string(),
    ])
    .env("FOG_INDEX_CHILD", "1")
    .env("FOG_INDEX_PORT", port.to_string())
    .env("FOG_INDEX_NETWORK", network)
    .stdin(Stdio::null())
    .stdout(log_file)
    .stderr(log_err);
    crate::process::detach_command(&mut cmd);
    let mut child = cmd
        .spawn()
        .map_err(|e| io::Error::other(format!("could not spawn index server: {e}")))?;
    let pid = child.id();
    // Record the pid so `maybe_terminate_if_no_instances` can find it later.
    let _ = std::fs::write(index_pid_path(port), pid.to_string());
    // Wait for it to bind before reporting success (mirrors `daemonize`).
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(10);
    loop {
        if server_started(port) {
            println!("index server started in background (pid {pid}) on :{port}");
            println!("  status: curl http://127.0.0.1:{port}/api/services");
            println!("  stop:   fog index kill");
            println!("  logs:   {}", log_dir.join("daemon.log").display());
            println!("  log dir: {}", log_dir.display());
            return Ok(());
        }
        if child.try_wait().ok().flatten().is_some() {
            let _ = std::fs::remove_file(index_pid_path(port));
            return Err(io::Error::other(format!(
                "index server (pid {pid}) exited during startup; logs: {}",
                log_dir.display()
            )));
        }
        if std::time::Instant::now() >= deadline {
            return Err(io::Error::other(format!(
                "index server (pid {pid}) did not bind within 10s; logs: {}",
                log_dir.display()
            )));
        }
        std::thread::sleep(std::time::Duration::from_millis(100));
    }
}

/// Runs the index server in the foreground until killed. Used by
/// `fog index serve --foreground` and by the detached child spawned in
/// [`serve_detached`] (which sets `FOG_INDEX_CHILD=1`).
pub fn serve_foreground(port: u16, network: String) -> io::Result<()> {
    // Drop the detach marker so it does not leak into spawned helpers.
    // SAFETY: the process is still single-threaded at this point.
    if std::env::var_os("FOG_INDEX_CHILD").is_some() {
        unsafe { std::env::remove_var("FOG_INDEX_CHILD") };
    }
    serve_blocking(port, network)
}

/// Launches the index server as a detached background process (`fog index
/// serve --foreground` as the child), so it survives any individual fog
/// instance exiting. If it is already running this is a no-op.
fn spawn_server(cfg: &RouterConfig) -> Result<(), String> {
    let port = cfg.index_port.unwrap_or(DEFAULT_INDEX_PORT);
    if server_started(port) {
        return Ok(());
    }
    let log_dir = index_log_dir(port);
    let _ = std::fs::create_dir_all(&log_dir);
    restrict_permissions(&log_dir, 0o700);
    let log_file = std::fs::File::create(log_dir.join("daemon.log")).and_then(|f| {
        let err = f.try_clone()?;
        Ok((f, err))
    });
    restrict_permissions(&log_dir.join("daemon.log"), 0o600);
    let exe = std::env::current_exe().unwrap_or_else(|_| std::path::PathBuf::from("fog"));
    let mut cmd = std::process::Command::new(&exe);
    // `--foreground`: the child must block; this parent does the detaching.
    // (Plain `index serve` now detaches itself, which would double-fork here.)
    cmd.args([
        "index",
        "serve",
        "--foreground",
        "--port",
        &port.to_string(),
    ])
    .env("FOG_INDEX_CHILD", "1")
    .env("FOG_INDEX_PORT", port.to_string())
    .env("FOG_INDEX_NETWORK", &cfg.shared_network)
    .stdin(std::process::Stdio::null());
    match log_file {
        Ok((out, err)) => {
            cmd.stdout(out).stderr(err);
        }
        Err(_) => {
            cmd.stdout(std::process::Stdio::null())
                .stderr(std::process::Stdio::null());
        }
    }
    crate::process::detach_command(&mut cmd);
    let mut child = cmd
        .spawn()
        .map_err(|e| format!("could not spawn index server: {e}"))?;
    let pid = child.id();
    // Record the pid so `maybe_terminate_if_no_instances` can find it later.
    let _ = std::fs::write(index_pid_path(port), pid.to_string());
    // Wait briefly for it to bind before reporting success.
    for _ in 0..25 {
        if server_started(port) {
            return Ok(());
        }
        if child.try_wait().ok().flatten().is_some() {
            let _ = std::fs::remove_file(index_pid_path(port));
            return Err(format!("index server (pid {pid}) exited during startup"));
        }
        std::thread::sleep(std::time::Duration::from_millis(200));
    }
    // Timed out — clean up the stale pidfile if the server never came up.
    if !server_started(port) {
        let _ = std::fs::remove_file(index_pid_path(port));
    }
    Err(format!("index server (pid {pid}) did not bind within 5s"))
}

/// Entry point for the `fog index serve` subcommand without flags.
/// Kept for programmatic use: runs the standalone index server in the
/// foreground until killed (env `FOG_INDEX_PORT`/`FOG_INDEX_NETWORK`).
/// The CLI (`main.rs`) detaches by default and only calls this via
/// `--foreground`.
pub fn serve() -> io::Result<()> {
    let port: u16 = std::env::var("FOG_INDEX_PORT")
        .ok()
        .and_then(|p| p.parse().ok())
        .unwrap_or(DEFAULT_INDEX_PORT);
    let network = std::env::var("FOG_INDEX_NETWORK").unwrap_or_else(|_| "fog-router".to_string());
    serve_blocking(port, network)
}

/// Blocks forever serving the embedded SPA on loopback `port` (127.0.0.1 only).
/// Write paths (`POST /api/instances/*/services/*/action`, `/kill`, `/launch`,
/// `/api/server/*`) are localhost-only by bind address — do not expose this
/// port externally. Any local process can still call them.
fn serve_blocking(port: u16, network: String) -> io::Result<()> {
    CURRENT_INDEX_PORT.store(port, std::sync::atomic::Ordering::SeqCst);
    // Record this server's pid for `maybe_terminate_if_no_instances`.
    let _ = std::fs::write(index_pid_path(port), std::process::id().to_string());
    // Self-terminate when no fog instance has been alive for a while, so a
    // crashed last instance (no cleanup hook) still brings the server down.
    std::thread::spawn(move || {
        let mut idle_ticks: u32 = 0;
        loop {
            std::thread::sleep(std::time::Duration::from_secs(5));
            let instances = crate::ipc::find_instances().unwrap_or_default();
            let any_alive = instances
                .iter()
                .any(|(_, p)| crate::ipc::query_status(p).is_ok());
            if any_alive {
                idle_ticks = 0;
            } else {
                idle_ticks += 1;
                // 4 ticks = ~20s of continuous idleness before exiting.
                if idle_ticks >= 4 {
                    let _ = std::fs::remove_file(index_pid_path(port));
                    std::process::exit(0);
                }
            }
        }
    });

    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|e| io::Error::other(e.to_string()))?;
    let result = rt.block_on(serve_listener(port, network));
    let _ = std::fs::remove_file(index_pid_path(port));
    result
}

/// Binds loopback `port` and serves the embedded index API until the listener
/// fails. Shared by [`serve_blocking`] (production) and [`serve_for_test`].
async fn serve_listener(port: u16, network: String) -> io::Result<()> {
    let addr = format!("127.0.0.1:{port}");
    let listener = tokio::net::TcpListener::bind(&addr)
        .await
        .map_err(|e| io::Error::other(format!("bind {addr}: {e}")))?;
    // The embedded index server is where the web UI (and, via the vite dev
    // proxy, the dev UI) is actually reached, so it must serve the built-in
    // terminal gateway too — otherwise `/ws/terminal` would fall through to
    // the SPA fallback and the browser upgrade would fail. The standalone
    // server uses the gateway's default hardening limits (it has no
    // per-script `TerminalConfig`).
    let terminal = std::sync::Arc::new(crate::config::TerminalConfig::default());
    let terminal_sessions = std::sync::Arc::new(crate::terminal_ws::SessionsRegistry::default());
    loop {
        let Ok((stream, peer)) = listener.accept().await else {
            continue;
        };
        let peer_ip = peer.ip().to_string();
        let io = TokioIo::new(stream);
        let network = network.clone();
        let terminal = terminal.clone();
        let terminal_sessions = terminal_sessions.clone();
        tokio::spawn(async move {
            let svc = service_fn(move |req: Request<hyper::body::Incoming>| {
                let network = network.clone();
                let terminal = terminal.clone();
                let terminal_sessions = terminal_sessions.clone();
                let peer_ip = peer_ip.clone();
                async move { serve_index(&network, req, terminal, terminal_sessions, peer_ip).await }
            });
            let _ = http1::Builder::new()
                .serve_connection(io, svc)
                .with_upgrades()
                .await;
        });
    }
}

/// Test-only entry point: serves the embedded index API on loopback `port`
/// without the idle self-terminate watchdog or the pidfile that
/// [`serve_blocking`] installs, so an integration test can drive the HTTP
/// surface on a thread. Blocks until the process exits.
#[doc(hidden)]
pub fn serve_for_test(port: u16) -> io::Result<()> {
    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|e| io::Error::other(e.to_string()))?;
    rt.block_on(serve_listener(port, "fog-test".to_string()))
}

/// Maps a file path to a media type for the `Content-Type` header.
#[allow(dead_code)] // only reachable through build-generated code when SPA exists
fn mime_for(path: &str) -> &'static str {
    let ext = path.rsplit('.').next().unwrap_or("");
    match ext {
        "html" | "htm" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" => "application/json",
        "map" => "application/json",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "avif" => "image/avif",
        "ico" => "image/x-icon",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "ttf" => "font/ttf",
        "otf" => "font/otf",
        "wasm" => "application/wasm",
        "webmanifest" => "application/manifest+json",
        "txt" => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

/// Serializes a value to JSON and returns it as an `application/json` response.
fn json_response<T: serde::Serialize>(value: &T) -> Response<RespBody> {
    let body = serde_json::to_vec(value).unwrap_or_else(|_| b"{}".to_vec());
    Response::builder()
        .status(StatusCode::OK)
        .header("content-type", "application/json")
        .header("cache-control", "no-cache")
        .body(Full::new(Bytes::from(body)).boxed())
        .expect("response builder failed")
}

/// A JSON 404 for unknown `/api/*` routes.
fn api_not_found() -> Response<RespBody> {
    Response::builder()
        .status(StatusCode::NOT_FOUND)
        .header("content-type", "application/json")
        .body(Full::new(Bytes::from(b"{\"error\":\"not found\"}".to_vec())).boxed())
        .expect("response builder failed")
}

/// Builds a JSON error response `{"error":"<message>"}` with the given status.
/// Used by the service-action route for its validation and upstream failures.
fn api_error(status: StatusCode, message: &str) -> Response<RespBody> {
    let body = serde_json::to_vec(&serde_json::json!({ "error": message }))
        .unwrap_or_else(|_| b"{}".to_vec());
    Response::builder()
        .status(status)
        .header("content-type", "application/json")
        .body(Full::new(Bytes::from(body)).boxed())
        .expect("response builder failed")
}

/// A running fog instance, listed in the log viewer's picker.
struct FogInstance {
    /// The fog process PID (its socket is `$TMPDIR/fog-<pid>.sock`).
    pid: u32,
    /// The script the instance is running (e.g. `dev`).
    script: String,
    /// Live service status snapshots.
    services: Vec<crate::ipc::ServiceStatus>,
    /// Absolute path to the instance's config dir (its `fog.json`'s parent),
    /// if reported by the instance.
    config_dir: Option<String>,
    /// Git project identity of the instance (from `IpcState.project`).
    project: Option<String>,
    /// Branch the instance serves (from `IpcState.branch`).
    branch: Option<String>,
    /// Allocated ports for this instance.
    ports: crate::ipc::PortMap,
    /// Native routes (templates) for this instance.
    native_routes: Vec<crate::ipc::NativeRouteInfo>,
}

/// Extracts a query parameter value by name from a URI query string.
fn query_param(query: Option<&str>, name: &str) -> Option<String> {
    query?.split('&').find_map(|pair| {
        let mut it = pair.splitn(2, '=');
        let key = it.next()?;
        if key == name {
            Some(it.next().unwrap_or("").to_string())
        } else {
            None
        }
    })
}

/// Resolves a `?service=<name>` attach target to a working-directory shell.
///
/// This is a *working-directory* attach (pattern B), not a live PTY attach:
/// the managed service's PTY lives in its own fog daemon process and is only
/// reachable over IPC, so the web terminal cannot share that exact master.
/// Instead the shell opens in the service's working directory (its `path`,
/// resolved against the instance's config dir) with the service's env, which
/// gives the user a terminal that behaves as if it is inside the running
/// service. The service process itself is never touched and keeps running
/// regardless of the terminal session.
///
/// Returns `None` when no running instance reports a running service of that
/// name, or when the instance's config dir is unknown.
pub fn resolve_service_target(service: &str) -> Option<crate::terminal_ws::ServiceTarget> {
    use std::path::Path;
    let inst = discover_fog_instances()
        .into_iter()
        .find(|i| i.services.iter().any(|s| s.name == service && s.running))?;
    let config_dir = std::path::PathBuf::from(inst.config_dir.clone()?);
    let mut cwd = config_dir.clone();
    let mut env: Vec<(String, String)> = Vec::new();
    // Best-effort: load the instance's fog.json to refine the service's
    // working directory (its `path`) and surface its declared env vars. If the
    // config cannot be read or the entry not found, fall back to the instance
    // config dir, which is still a sensible shell root for the project.
    if let Ok(cfg) = crate::config::load(&config_dir.join("fog.json")) {
        for script in cfg.scripts.values() {
            if let Some(entries) = &script.service {
                for e in entries {
                    let name = e.name.clone().unwrap_or_else(|| {
                        Path::new(&e.path)
                            .file_name()
                            .unwrap_or_default()
                            .to_string_lossy()
                            .into_owned()
                    });
                    if name == service {
                        cwd = config_dir.join(&e.path);
                        if let Some(env_map) = &e.env {
                            env = env_map
                                .iter()
                                .map(|(k, v)| (k.clone(), v.clone()))
                                .collect();
                        }
                        break;
                    }
                }
            }
        }
    }
    Some(crate::terminal_ws::ServiceTarget { cwd, env })
}

/// Parses a URL query string into a map of unquoted key/value pairs.
fn parse_query(query: &str) -> std::collections::HashMap<String, String> {
    let mut out = std::collections::HashMap::new();
    for pair in query.split('&').filter(|p| !p.is_empty()) {
        let (k, v) = pair.split_once('=').unwrap_or((pair, ""));
        out.insert(k.to_string(), v.to_string());
    }
    out
}

fn command_exists(name: &str) -> bool {
    crate::process::command_exists(name)
}

#[cfg(test)]
mod tests {
    use super::api::{api_service_from, entry_url};
    use super::assets::{accepts_encoding, asset_response};
    use super::discovery::{
        derive_group, docker_host_port, extract_hosts, git_project_for, infra_branch,
        reachable_entries_from,
    };
    use super::http::{
        handle_action_request, json_content_type_allowed, parse_action_route, write_request_allowed,
    };
    use super::icons::{
        IconSource, MAX_ICON_BYTES, encode_path_segment, is_icon_path, parse_project_icon_route,
        resolve_icon_file, resolve_project_icon, serve_icon_file,
    };
    use super::launch::{
        api_launch_targets_method, build_launch_targets, handle_launch_request, launch_project_for,
    };
    use super::logs::{
        is_valid_container, is_valid_service_name, parse_docker_timestamp, slice_log_window,
        split_docker_log_line, sse_event,
    };
    use super::*;
    use std::thread;

    #[test]
    fn test_index_log_dir_naming() {
        assert_eq!(
            index_log_dir(18080),
            std::env::temp_dir().join("fog-index-18080.logs")
        );
    }

    #[test]
    fn test_resolve_serve_port_explicit_wins() {
        // Explicit --port always wins regardless of env/config.
        assert_eq!(resolve_serve_port(Some(18991)), 18991);
    }

    #[test]
    fn test_resolve_project_icon_classifies() {
        assert!(matches!(
            resolve_project_icon("https://example.com/logo.png"),
            Some(IconSource::Url(u)) if u == "https://example.com/logo.png"
        ));
        assert!(matches!(
            resolve_project_icon("  data:image/svg+xml;base64,PHN2Zw=="),
            Some(IconSource::Url(u)) if u == "data:image/svg+xml;base64,PHN2Zw=="
        ));
        assert!(matches!(
            resolve_project_icon("frontend/public/mark.svg"),
            Some(IconSource::Path(p)) if p == "frontend/public/mark.svg"
        ));
        assert!(matches!(
            resolve_project_icon("/abs/path/mark.png"),
            Some(IconSource::Path(_))
        ));
        // Non-renderable schemes and blank values are rejected.
        assert!(resolve_project_icon("javascript:alert(1)").is_none());
        assert!(resolve_project_icon("file:///etc/passwd").is_none());
        assert!(resolve_project_icon("   ").is_none());
    }

    #[test]
    fn test_encode_path_segment() {
        assert_eq!(encode_path_segment("red-fox"), "red-fox");
        assert_eq!(encode_path_segment("my project"), "my%20project");
        assert_eq!(encode_path_segment("a/b"), "a%2Fb");
    }

    fn headers(pairs: &[(&str, &str)]) -> hyper::HeaderMap {
        let mut h = hyper::HeaderMap::new();
        for (k, v) in pairs {
            h.insert(
                hyper::header::HeaderName::from_bytes(k.as_bytes()).unwrap(),
                hyper::header::HeaderValue::from_str(v).unwrap(),
            );
        }
        h
    }

    #[test]
    fn test_write_request_allowed_same_origin() {
        let h = headers(&[
            ("origin", "http://127.0.0.1:18080"),
            ("host", "127.0.0.1:18080"),
        ]);
        assert!(write_request_allowed(&h));
    }

    #[test]
    fn test_write_request_allowed_cross_origin() {
        let h = headers(&[
            ("origin", "http://evil.example"),
            ("host", "127.0.0.1:18080"),
        ]);
        assert!(!write_request_allowed(&h));
    }

    #[test]
    fn test_write_request_allowed_null_origin() {
        let h = headers(&[("origin", "null"), ("host", "127.0.0.1:18080")]);
        assert!(!write_request_allowed(&h));
    }

    #[test]
    fn test_write_request_allowed_no_headers_allows_curl() {
        assert!(write_request_allowed(&hyper::HeaderMap::new()));
    }

    #[test]
    fn test_write_request_allowed_origin_without_host() {
        let h = headers(&[("origin", "http://127.0.0.1:18080")]);
        assert!(!write_request_allowed(&h));
    }

    #[test]
    fn test_write_request_allowed_default_port_normalized() {
        let h = headers(&[("origin", "http://127.0.0.1"), ("host", "127.0.0.1:80")]);
        assert!(write_request_allowed(&h));
    }

    #[test]
    fn test_write_request_allowed_sec_fetch_site() {
        assert!(!write_request_allowed(&headers(&[(
            "sec-fetch-site",
            "cross-site",
        )])));
        assert!(!write_request_allowed(&headers(&[(
            "sec-fetch-site",
            "same-site",
        )])));
        assert!(write_request_allowed(&headers(&[(
            "sec-fetch-site",
            "same-origin",
        )])));
        assert!(write_request_allowed(&headers(&[(
            "sec-fetch-site",
            "none",
        )])));
    }

    #[test]
    fn test_json_content_type_allowed() {
        // Missing Content-Type is allowed (non-browser clients).
        assert!(json_content_type_allowed(&hyper::HeaderMap::new()));
        assert!(json_content_type_allowed(&headers(&[(
            "content-type",
            "application/json",
        )])));
        assert!(json_content_type_allowed(&headers(&[(
            "content-type",
            "application/json; charset=utf-8",
        )])));
        assert!(!json_content_type_allowed(&headers(&[(
            "content-type",
            "text/plain",
        )])));
        assert!(!json_content_type_allowed(&headers(&[(
            "content-type",
            "application/x-www-form-urlencoded",
        )])));
    }

    #[test]
    fn test_is_icon_path() {
        assert!(is_icon_path(std::path::Path::new("a/logo.svg")));
        assert!(is_icon_path(std::path::Path::new("a/LOGO.PNG")));
        assert!(!is_icon_path(std::path::Path::new("a/logo.txt")));
        assert!(!is_icon_path(std::path::Path::new("a/logo")));
    }

    #[test]
    fn test_resolve_icon_file_relative_absolute_and_missing() {
        let dir = std::env::temp_dir().join(format!("fog-icon-test-{}", std::process::id()));
        std::fs::create_dir_all(dir.join("assets")).unwrap();
        let file = dir.join("assets/mark.svg");
        std::fs::write(&file, "<svg/>").unwrap();

        // Relative resolves against the config dir; absolute is used as-is.
        assert_eq!(
            resolve_icon_file(&dir, "assets/mark.svg"),
            Some(file.canonicalize().unwrap())
        );
        assert_eq!(
            resolve_icon_file(&dir, file.to_str().unwrap()),
            Some(file.canonicalize().unwrap())
        );
        // Missing path yields None; a directory is not a file.
        assert!(resolve_icon_file(&dir, "assets/nope.svg").is_none());
        assert!(resolve_icon_file(&dir, "assets").is_none());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_serve_icon_file_headers_etag_and_size_cap() {
        let dir = std::env::temp_dir().join(format!("fog-icon-serve-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let file = dir.join("mark.svg");
        std::fs::write(&file, b"<svg/>").unwrap();

        let resp = serve_icon_file(&file, None);
        assert_eq!(resp.status(), StatusCode::OK);
        assert_eq!(resp.headers().get("content-type").unwrap(), "image/svg+xml");
        let etag = resp
            .headers()
            .get("etag")
            .unwrap()
            .to_str()
            .unwrap()
            .to_string();
        assert_eq!(
            serve_icon_file(&file, Some(&etag)).status(),
            StatusCode::NOT_MODIFIED
        );

        let big = dir.join("big.svg");
        std::fs::write(&big, vec![b'x'; (MAX_ICON_BYTES + 1) as usize]).unwrap();
        assert_eq!(
            serve_icon_file(&big, None).status(),
            StatusCode::PAYLOAD_TOO_LARGE
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_parse_project_icon_route() {
        assert_eq!(
            parse_project_icon_route("/api/projects/gems/icon"),
            Some("gems")
        );
        assert_eq!(
            parse_project_icon_route("/api/projects/my%20project/icon"),
            Some("my%20project")
        );
        assert_eq!(parse_project_icon_route("/api/projects/gems"), None);
        assert_eq!(parse_project_icon_route("/api/projects//icon"), None);
        assert_eq!(parse_project_icon_route("/api/services"), None);
    }

    #[test]
    fn test_query_param_extracts_value() {
        assert_eq!(
            query_param(Some("service=api&auth_token=abc"), "service"),
            Some("api".into())
        );
        assert_eq!(
            query_param(Some("service=api&auth_token=abc"), "auth_token"),
            Some("abc".into())
        );
        assert_eq!(query_param(Some("service="), "service"), Some("".into()));
        assert_eq!(query_param(Some("x=1"), "service"), None);
        assert_eq!(query_param(None, "service"), None);
    }

    #[test]
    fn test_extract_hosts_simple() {
        let hosts = extract_hosts("Host(`main.gems`)");
        assert_eq!(hosts, vec!["main.gems"]);
    }

    #[test]
    fn test_extract_hosts_multi() {
        let hosts = extract_hosts("Host(`main.gems`) || Host(`feature-x.gems`)");
        assert_eq!(hosts, vec!["main.gems", "feature-x.gems"]);
    }

    #[test]
    fn test_extract_hosts_regexp() {
        let hosts = extract_hosts("HostRegexp(`{host:.+}`)");
        assert_eq!(hosts, vec!["{host:.+}"]);
    }

    #[test]
    fn test_docker_host_port_extracts_number() {
        // The helper shells out to docker, so no live assertion is reliable;
        // just confirm it returns a value (or None) without panicking.
        let _ = docker_host_port("fog-router-traefik");
    }

    fn labels(pairs: &[(&str, &str)]) -> std::collections::HashMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect()
    }

    #[test]
    fn test_derive_group_app_project() {
        let l = labels(&[
            (
                "com.docker.compose.project.working_dir",
                "/Users/naputt/git/GEMS",
            ),
            ("com.docker.compose.project", "gems-main"),
        ]);
        assert_eq!(
            derive_group(&l, "gems-main-api-1", None),
            ("gems".into(), "main".into(), false)
        );
    }

    #[test]
    fn test_derive_group_app_feature_worktree() {
        let l = labels(&[
            (
                "com.docker.compose.project.working_dir",
                "/Users/naputt/git/GEMS",
            ),
            ("com.docker.compose.project", "gems-feature-x"),
        ]);
        assert_eq!(
            derive_group(&l, "gems-feature-x-api-1", None),
            ("gems".into(), "feature-x".into(), false)
        );
    }

    #[test]
    fn test_derive_group_infra_is_shared() {
        let l = labels(&[
            (
                "com.docker.compose.project.working_dir",
                "/Users/naputt/git/GEMS/infra",
            ),
            ("com.docker.compose.project", "gems-infra"),
        ]);
        assert_eq!(
            derive_group(&l, "gems-postgres", None),
            ("gems".into(), "shared".into(), true)
        );
    }

    #[test]
    fn test_derive_group_redfox_naming() {
        // red-fox app project is `redfox-main` (no dash in the base) and infra
        // is `red-fox-infra` under `infra/`; both must resolve to `red-fox`.
        let app = labels(&[
            (
                "com.docker.compose.project.working_dir",
                "/Users/naputt/code/red-fox",
            ),
            ("com.docker.compose.project", "redfox-main"),
        ]);
        assert_eq!(
            derive_group(&app, "redfox-main-api-1", None),
            ("red-fox".into(), "main".into(), false)
        );

        let infra = labels(&[
            (
                "com.docker.compose.project.working_dir",
                "/Users/naputt/code/red-fox/infra",
            ),
            ("com.docker.compose.project", "red-fox-infra"),
        ]);
        assert_eq!(
            derive_group(&infra, "red-fox-infra-postgres-1", None),
            ("red-fox".into(), "shared".into(), true)
        );
    }

    #[test]
    fn test_derive_group_infra_per_branch_containers() {
        // Each branch runs its own infra container
        // (`red-fox-infra-<branch>`): it must group under that branch, not
        // under `shared` and not under a stray branch-named project.
        let main = labels(&[
            (
                "com.docker.compose.project.working_dir",
                "/repo/red-fox/infra",
            ),
            ("com.docker.compose.project", "red-fox-infra-main"),
        ]);
        assert_eq!(
            derive_group(&main, "red-fox-infra-main-postgres-1", Some("red-fox")),
            ("red-fox".into(), "main".into(), false)
        );

        // The branch checkout lives outside its git repo (detached worktree
        // cache), so git resolution fails — the compose prefix still yields
        // the repo project instead of a stray branch-named one.
        let branch = labels(&[
            (
                "com.docker.compose.project.working_dir",
                "/tmp/worktrees/abc/feat-branch-specific-service/infra",
            ),
            (
                "com.docker.compose.project",
                "red-fox-infra-feat-branch-specific-service",
            ),
        ]);
        assert_eq!(
            derive_group(
                &branch,
                "red-fox-infra-feat-branch-specific-service-postgres-1",
                None
            ),
            (
                "red-fox".into(),
                "feat-branch-specific-service".into(),
                false
            )
        );
    }

    #[test]
    fn test_infra_branch_parsing() {
        assert_eq!(infra_branch("red-fox-infra"), None);
        assert_eq!(infra_branch("gems-infra"), None);
        assert_eq!(
            infra_branch("red-fox-infra-main"),
            Some(("red-fox".into(), "main".into()))
        );
        assert_eq!(
            infra_branch("red-fox-infra-feat-branch-specific-service"),
            Some(("red-fox".into(), "feat-branch-specific-service".into()))
        );
        assert_eq!(
            infra_branch("red_fox_infra_feat_branch"),
            Some(("red-fox".into(), "feat-branch".into()))
        );
    }

    #[test]
    fn test_derive_group_worktree_resolves_to_repo_root() {
        // Build a real repo + linked worktree so the git-based project
        // resolution runs: the worktree checkout dir is named after its branch
        // (`ui`) and must map back to the repository's project (`red-fox`).
        let base = std::env::temp_dir().join(format!("fog-index-derive-{}", std::process::id()));
        let repo = base.join("red-fox");
        std::fs::create_dir_all(&repo).unwrap();
        let run = |dir: &std::path::Path, args: &[&str]| {
            std::process::Command::new("git")
                .arg("-C")
                .arg(dir)
                .args(args)
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false)
        };
        if !run(&repo, &["init", "-q", "-b", "main"])
            || !run(&repo, &["config", "user.email", "test@example.com"])
            || !run(&repo, &["config", "user.name", "Test"])
        {
            let _ = std::fs::remove_dir_all(&base);
            eprintln!("skipping: could not init repo");
            return;
        }
        std::fs::write(repo.join("fog.json"), "{}").unwrap();
        run(&repo, &["add", "fog.json"]);
        run(&repo, &["commit", "-q", "-m", "init"]);
        let worktree = base.join("ui");
        if !run(
            &repo,
            &["worktree", "add", "-q", &worktree.to_string_lossy()],
        ) {
            let _ = std::fs::remove_dir_all(&base);
            eprintln!("skipping: could not add worktree");
            return;
        }

        let app = labels(&[
            (
                "com.docker.compose.project.working_dir",
                worktree.to_str().unwrap(),
            ),
            ("com.docker.compose.project", "redfox-ui"),
        ]);
        let git_project = git_project_for(worktree.to_str().unwrap());
        assert_eq!(
            derive_group(&app, "redfox-ui-frontend-1", git_project.as_deref()),
            ("red-fox".into(), "ui".into(), false)
        );

        let infra_dir = worktree.join("infra");
        std::fs::create_dir_all(&infra_dir).unwrap();
        let infra_git = git_project_for(infra_dir.to_str().unwrap());
        let infra = labels(&[
            (
                "com.docker.compose.project.working_dir",
                infra_dir.to_str().unwrap(),
            ),
            ("com.docker.compose.project", "red-fox-infra"),
        ]);
        assert_eq!(
            derive_group(&infra, "red-fox-infra-postgres-1", infra_git.as_deref()),
            ("red-fox".into(), "shared".into(), true)
        );

        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn test_derive_group_no_labels_falls_back_to_name() {
        let l = labels(&[]);
        let (p, w, s) = derive_group(&l, "barecontainer", None);
        assert_eq!(p, "barecontainer");
        assert_eq!(w, "main");
        assert!(!s);

        // A dashed name without a working-dir falls back to the base (prefix
        // before the first `-`).
        let (p, w, _) = derive_group(&l, "gems-main", None);
        assert_eq!(p, "gems");
        assert_eq!(w, "main");
    }

    #[test]
    fn test_derive_group_git_project_unifies_worktrees() {
        // admin/ and ui/ are separate worktrees of the same repo; the
        // git-derived project groups both under red-fox.
        let app = labels(&[
            (
                "com.docker.compose.project.working_dir",
                "/Users/naputt/code/red-fox/ui",
            ),
            ("com.docker.compose.project", "redfox-ui"),
        ]);
        let (p, w, s) = derive_group(&app, "redfox-ui-frontend-1", Some("red-fox"));
        assert_eq!((p.as_str(), w.as_str(), s), ("red-fox", "ui", false));

        // Shared infra of any worktree stays under the same project.
        let infra = labels(&[
            (
                "com.docker.compose.project.working_dir",
                "/Users/naputt/code/red-fox/ui/infra",
            ),
            ("com.docker.compose.project", "red-fox-infra"),
        ]);
        let (p, w, s) = derive_group(&infra, "red-fox-infra-postgres-1", Some("red-fox"));
        assert_eq!((p.as_str(), w.as_str(), s), ("red-fox", "shared", true));

        // Without the git override, the working-dir basename wins (old
        // behavior) — the override is what fixes the multi-worktree case.
        let (p, w, s) = derive_group(&app, "redfox-ui-frontend-1", None);
        assert_eq!((p.as_str(), w.as_str(), s), ("ui", "ui", false));
    }

    #[test]
    fn test_project_name_from_common_dir() {
        assert_eq!(
            project_name_from_common_dir("/Users/naputt/code/red-fox/.git"),
            "red-fox"
        );
        assert_eq!(
            project_name_from_common_dir("/Users/naputt/git/GEMS/.git"),
            "gems"
        );
        // A non-`.git` path uses its own basename.
        assert_eq!(
            project_name_from_common_dir("/repo/my-project"),
            "my-project"
        );
    }

    #[test]
    fn test_parse_docker_timestamp() {
        // Known epoch.
        assert_eq!(parse_docker_timestamp("1970-01-01T00:00:00Z"), Some(0));
        assert_eq!(
            parse_docker_timestamp("2021-01-01T00:00:00Z"),
            Some(1_609_459_200)
        );
        assert_eq!(
            parse_docker_timestamp("2026-08-15T05:12:52Z"),
            Some(1_786_770_772)
        );
        // Fractional seconds are ignored (epoch seconds).
        assert_eq!(
            parse_docker_timestamp("2026-08-15T05:12:52.383339801Z"),
            Some(1_786_770_772)
        );
        // Malformed input.
        assert_eq!(parse_docker_timestamp(""), None);
        assert_eq!(parse_docker_timestamp("2026-08-15"), None);
        assert_eq!(parse_docker_timestamp("2026-13-01T00:00:00Z"), None);
        assert_eq!(parse_docker_timestamp("2026-08-15T24:00:00Z"), None);
        assert_eq!(parse_docker_timestamp("hello"), None);
    }

    #[test]
    fn test_split_docker_log_line_and_sse_event() {
        let (secs, body) =
            split_docker_log_line("2026-08-15T05:12:52.383339801Z hello world").unwrap();
        assert_eq!(secs, 1_786_770_772);
        assert_eq!(body, "hello world");

        let evt = sse_event("2026-08-15T05:12:52.383339801Z hello world");
        assert_eq!(evt, "id: 1786770772\ndata: hello world\n\n");

        // A line without a timestamp still streams, just without an id.
        let evt = sse_event("plain log line");
        assert_eq!(evt, "data: plain log line\n\n");
    }

    #[test]
    fn test_is_valid_container() {
        assert!(is_valid_container("redfox-main-api-1"));
        assert!(is_valid_container("fog-router-traefik"));
        assert!(is_valid_container("my.container_01-x"));
        assert!(!is_valid_container(""));
        assert!(!is_valid_container("../../etc/passwd"));
        assert!(!is_valid_container("-leading-dash"));
        assert!(!is_valid_container("a b"));
        assert!(!is_valid_container("a;rm -rf /"));
        assert!(!is_valid_container("a".repeat(256).as_str()));
    }

    #[test]
    fn test_parse_query() {
        let q = parse_query("service=abc&tail=50");
        assert_eq!(q.get("service").map(String::as_str), Some("abc"));
        assert_eq!(q.get("tail").map(String::as_str), Some("50"));
        assert_eq!(parse_query("").len(), 0);
    }

    #[test]
    fn test_slice_log_window() {
        // `all` is the capped fetch of newest `need = tail + offset + 1`
        // lines; hitting the cap exactly means older lines remain.
        let (w, more) = slice_log_window(vec!["l4".into(), "l5".into(), "l6".into()], 2, 0);
        assert_eq!(w, vec!["l5", "l6"]);
        assert!(more);
        // Uncapped fetch: whole log present, no more.
        let (w, more) = slice_log_window(vec!["l1".into(), "l2".into()], 2, 0);
        assert_eq!(w, vec!["l1", "l2"]);
        assert!(!more);
        // Offset window: skip newest 1, take previous 2 (uncapped).
        let (w, more) = slice_log_window(vec!["l1".into(), "l2".into(), "l3".into()], 2, 1);
        assert_eq!(w, vec!["l1", "l2"]);
        assert!(!more);
        // Offset past the end yields nothing.
        let (w, _) = slice_log_window(vec!["l1".into(), "l2".into()], 2, 10);
        assert!(w.is_empty());
    }

    #[test]
    fn test_is_valid_service_name() {
        assert!(is_valid_service_name("web"));
        assert!(is_valid_service_name("proxy"));
        assert!(is_valid_service_name("daemon"));
        assert!(is_valid_service_name("my service-v2"));
        assert!(!is_valid_service_name(""));
        assert!(!is_valid_service_name("../etc/passwd"));
        assert!(!is_valid_service_name("a/b"));
        assert!(!is_valid_service_name("a".repeat(256).as_str()));
    }

    #[test]
    fn test_accepts_encoding() {
        assert!(accepts_encoding("gzip, deflate, br", "br"));
        assert!(accepts_encoding("gzip, deflate, br", "gzip"));
        assert!(!accepts_encoding("gzip, deflate, br", "zstd"));
        assert!(accepts_encoding("br;q=0.8, gzip;q=0.5", "br"));
        assert!(accepts_encoding("BR", "br"));
        // Explicit `q=0` refusal wins, even with a wildcard present.
        assert!(!accepts_encoding("gzip;q=0, *", "gzip"));
        assert!(accepts_encoding("*", "br"));
        assert!(!accepts_encoding("", "br"));
        assert!(!accepts_encoding("gzip", "br"));
    }

    fn test_asset(data: &'static [u8]) -> EmbeddedAsset {
        EmbeddedAsset {
            data,
            mime: "text/javascript; charset=utf-8",
            gzip: Some(b"gz-bytes" as &[u8]),
            br: Some(b"br-bytes" as &[u8]),
        }
    }

    #[tokio::test]
    async fn test_asset_response_prefers_brotli() {
        let resp = asset_response(
            test_asset(b"raw-bytes" as &[u8]),
            "/assets/app-abc123.js",
            "gzip, deflate, br",
        );
        let headers = resp.headers();
        assert_eq!(headers.get("content-encoding").unwrap(), "br");
        assert_eq!(headers.get("vary").unwrap(), "accept-encoding");
        assert_eq!(
            headers.get("cache-control").unwrap(),
            "public, max-age=31536000, immutable"
        );
        assert_eq!(body_bytes(resp).await, b"br-bytes");
    }

    #[tokio::test]
    async fn test_asset_response_gzip_when_no_brotli_offered() {
        let resp = asset_response(
            test_asset(b"raw-bytes" as &[u8]),
            "/assets/app-abc123.js",
            "gzip",
        );
        assert_eq!(resp.headers().get("content-encoding").unwrap(), "gzip");
        assert_eq!(body_bytes(resp).await, b"gz-bytes");
    }

    #[tokio::test]
    async fn test_asset_response_identity_without_accept_encoding() {
        let resp = asset_response(
            test_asset(b"raw-bytes" as &[u8]),
            "/assets/app-abc123.js",
            "",
        );
        assert!(resp.headers().get("content-encoding").is_none());
        // Vary is still advertised: the representation depends on the header.
        assert_eq!(resp.headers().get("vary").unwrap(), "accept-encoding");
        assert_eq!(body_bytes(resp).await, b"raw-bytes");
    }

    #[tokio::test]
    async fn test_asset_response_entry_html_is_not_cached() {
        // `index.html` is unhashed: clients must revalidate so deploys land.
        let resp = asset_response(test_asset(b"<html>" as &[u8]), "/index.html", "br");
        assert_eq!(resp.headers().get("cache-control").unwrap(), "no-cache");
        assert_eq!(body_bytes(resp).await, b"br-bytes");
    }

    #[tokio::test]
    async fn test_asset_response_uncompressed_asset_has_no_vary() {
        let asset = EmbeddedAsset {
            data: b"raw" as &[u8],
            mime: "font/woff2",
            gzip: None,
            br: None,
        };
        let resp = asset_response(asset, "/assets/font-abc.woff2", "gzip, br");
        assert!(resp.headers().get("content-encoding").is_none());
        assert!(resp.headers().get("vary").is_none());
        assert_eq!(body_bytes(resp).await, b"raw");
    }

    #[test]
    fn test_mime_for() {
        assert_eq!(mime_for("index.html"), "text/html; charset=utf-8");
        assert_eq!(mime_for("assets/app.js"), "text/javascript; charset=utf-8");
        assert_eq!(mime_for("style.css"), "text/css; charset=utf-8");
        assert_eq!(mime_for("logo.svg"), "image/svg+xml");
        assert_eq!(mime_for("font.woff2"), "font/woff2");
        assert_eq!(mime_for("data.bin"), "application/octet-stream");
        assert_eq!(mime_for("noext"), "application/octet-stream");
    }

    #[test]
    fn test_entry_url() {
        let http = IndexEntry {
            project: "gems".into(),
            worktree: "main".into(),
            shared: false,
            container: "gems-main-api-1".into(),
            service: "api".into(),
            hostname: "main.gems".into(),
            port: "8082".into(),
            published: vec![],
            raw_port: None,
            tls: true,
        };
        assert_eq!(entry_url(&http), "https://main.gems/");

        let raw = IndexEntry {
            project: "gems".into(),
            worktree: "shared".into(),
            shared: true,
            container: "gems-postgres".into(),
            service: "postgres".into(),
            hostname: "main.postgres.gems".into(),
            port: String::new(),
            published: vec![],
            raw_port: Some("55274".into()),
            tls: false,
        };
        assert_eq!(entry_url(&raw), "http://main.postgres.gems:55274/");
    }

    #[test]
    fn test_api_service_serialization() {
        let entry = IndexEntry {
            project: "gems".into(),
            worktree: "main".into(),
            shared: false,
            container: "gems-main-api-1".into(),
            service: "api".into(),
            hostname: "main.gems".into(),
            port: "8082".into(),
            published: vec!["0.0.0.0:8082->8082/tcp".into()],
            raw_port: Some("8082".into()),
            tls: true,
        };
        let svc = api_service_from(entry);
        let json = serde_json::to_value(&svc).unwrap();
        assert_eq!(json["project"], "gems");
        assert_eq!(json["worktree"], "main");
        assert_eq!(json["service"], "api");
        assert_eq!(json["container"], "gems-main-api-1");
        assert_eq!(json["status"], "running");
        assert_eq!(json["url"], "https://main.gems/");
        assert_eq!(json["ports"][0], "0.0.0.0:8082->8082/tcp");
        assert_eq!(json["health"], "unknown");
    }

    #[test]
    fn test_api_health_serialization() {
        let health = serde_json::json!({
            "health": [{
                "pid": 1234,
                "script": "dev",
                "service": "web",
                "running": true,
                "health": "healthy",
            }]
        });
        let json = serde_json::to_string(&health).unwrap();
        assert!(json.contains("\"service\":\"web\""));
        assert!(json.contains("\"health\":\"healthy\""));
    }

    #[test]
    fn test_embedded_get_missing_is_none() {
        // With no frontend build, embedded_get must return None so the server
        // falls back gracefully (this also guards the "ui/dist absent" build).
        let _ = embedded_get("/nonexistent.js");
        let _ = embedded_get("/");
    }

    /// Reads a response body to bytes for assertions.
    async fn body_bytes(resp: Response<RespBody>) -> Vec<u8> {
        use http_body_util::BodyExt;
        resp.into_body()
            .collect()
            .await
            .unwrap()
            .to_bytes()
            .to_vec()
    }

    #[tokio::test]
    async fn test_action_route_dispatch() {
        // A resolver that always returns a socket path that does not exist, so
        // the handler reaches the "instance not found" branch for valid POSTs.
        let no_socket = |_: u32| std::env::temp_dir().join("fog-action-nonexistent-zz.sock");

        // Valid POST to a pid with no socket file -> 404 (instance not found);
        // this proves the handler runs past method/pid/action parsing.
        let resp = handle_action_request(
            &hyper::Method::POST,
            "424242",
            "web",
            b"{\"action\":\"start\"}",
            no_socket,
        )
        .await;
        assert_eq!(resp.status(), StatusCode::NOT_FOUND);

        // Invalid action value -> 400 invalid action.
        let resp = handle_action_request(
            &hyper::Method::POST,
            "424242",
            "web",
            b"{\"action\":\"fly\"}",
            no_socket,
        )
        .await;
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
        assert!(String::from_utf8_lossy(&body_bytes(resp).await).contains("invalid action"));

        // Missing action -> 400 invalid action.
        let resp =
            handle_action_request(&hyper::Method::POST, "424242", "web", b"{}", no_socket).await;
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);

        // Non-numeric pid -> 400 invalid pid.
        let resp = handle_action_request(
            &hyper::Method::POST,
            "not-a-pid",
            "web",
            b"{\"action\":\"start\"}",
            no_socket,
        )
        .await;
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
        assert!(String::from_utf8_lossy(&body_bytes(resp).await).contains("invalid pid"));

        // A non-POST method on the action path must not run an action: 404.
        let resp = handle_action_request(
            &hyper::Method::GET,
            "424242",
            "web",
            b"{\"action\":\"start\"}",
            no_socket,
        )
        .await;
        assert_ne!(resp.status(), StatusCode::OK);
        assert_eq!(resp.status(), StatusCode::NOT_FOUND);
    }

    #[tokio::test]
    async fn test_action_route_parse() {
        assert_eq!(
            parse_action_route("/api/instances/1234/services/web/action"),
            Some(("1234", "web"))
        );
        assert_eq!(
            parse_action_route("/api/instances/1/services/a-b/action"),
            Some(("1", "a-b"))
        );
        // Wrong shape / extra segments / wrong prefix must not match.
        assert_eq!(parse_action_route("/api/instances/1234"), None);
        assert_eq!(parse_action_route("/api/instances/1234/services/web"), None);
        assert_eq!(
            parse_action_route("/api/instances/1234/services/web/action/extra"),
            None
        );
        assert_eq!(
            parse_action_route("/api/instances/1234/other/web/action"),
            None
        );
        assert_eq!(parse_action_route("/api/services"), None);
        assert_eq!(parse_action_route("/"), None);
    }

    /// Binds a real `UnixListener` that mimics a fog instance's IPC socket:
    /// accepts one connection, verifies the request is a `service_action` line,
    /// and replies with the given `ControlResponse`-shaped JSON.
    fn spawn_fake_instance(path: &std::path::Path, reply: &str) -> thread::JoinHandle<()> {
        use std::io::{BufRead, Write};
        let listener = crate::ipc::transport::Listener::bind(path).unwrap();
        let reply = reply.to_string();
        thread::spawn(move || {
            let mut stream = listener.accept().unwrap();
            let mut reader = std::io::BufReader::new(stream.try_clone().unwrap());
            let mut line = String::new();
            reader.read_line(&mut line).unwrap();
            assert!(
                line.starts_with("{\"type\":\"service_action\""),
                "unexpected request line: {line}"
            );
            writeln!(stream, "{reply}").unwrap();
        })
    }

    #[tokio::test]
    async fn test_action_route_forwards_ok() {
        let path = std::env::temp_dir().join(format!("fog-action-ok-{}.sock", std::process::id()));
        let _ = std::fs::remove_file(&path);
        let server = spawn_fake_instance(&path, r#"{"ok":true,"reason":""}"#);

        let socket = path.clone();
        let resp = handle_action_request(
            &hyper::Method::POST,
            "12345",
            "web",
            b"{\"action\":\"restart\"}",
            move |_| socket.clone(),
        )
        .await;
        server.join().unwrap();
        let _ = std::fs::remove_file(&path);

        assert_eq!(resp.status(), StatusCode::OK);
        let json: serde_json::Value = serde_json::from_slice(&body_bytes(resp).await).unwrap();
        assert_eq!(json["ok"], true);
        assert_eq!(json["reason"], "");
    }

    #[tokio::test]
    async fn test_action_route_forwards_refused() {
        let path =
            std::env::temp_dir().join(format!("fog-action-refused-{}.sock", std::process::id()));
        let _ = std::fs::remove_file(&path);
        let server = spawn_fake_instance(&path, r#"{"ok":false,"reason":"boom"}"#);

        let socket = path.clone();
        let resp = handle_action_request(
            &hyper::Method::POST,
            "12345",
            "web",
            b"{\"action\":\"stop\"}",
            move |_| socket.clone(),
        )
        .await;
        server.join().unwrap();
        let _ = std::fs::remove_file(&path);

        // The instance refused the action, but the forward itself succeeded:
        // still a 200, with the verdict surfaced in the body.
        assert_eq!(resp.status(), StatusCode::OK);
        let json: serde_json::Value = serde_json::from_slice(&body_bytes(resp).await).unwrap();
        assert_eq!(json["ok"], false);
        assert_eq!(json["reason"], "boom");
    }

    /// Creates a unique temp directory for a test and returns its path.
    fn test_dir(tag: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("fog-launch-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn test_launch_target_non_git_fallback_with_scripts() {
        // A plain directory (not a git repo) with a fog.json must surface as a
        // single project with a single worktree (the root) and its scripts.
        let dir = test_dir("non-git");
        std::fs::write(
            dir.join("fog.json"),
            r#"{"scripts":{"dev":{},"prod":{},"lint":{}}}"#,
        )
        .unwrap();

        let project = launch_project_for(&dir);
        assert_eq!(project.name, dir.file_name().unwrap().to_string_lossy());
        assert_eq!(project.path, dir.to_string_lossy());
        assert_eq!(
            project.worktrees.len(),
            1,
            "non-git fallback is one worktree"
        );
        let wt = &project.worktrees[0];
        assert_eq!(wt.path, dir.to_string_lossy());
        assert_eq!(wt.branch, None, "non-git fallback has no branch");
        assert_eq!(
            wt.scripts,
            vec!["dev", "lint", "prod"],
            "scripts are sorted"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_launch_target_empty_scripts_without_fog_json() {
        // A directory without fog.json still appears as a launchable target,
        // just with no scripts.
        let dir = test_dir("no-config");
        let project = launch_project_for(&dir);
        assert_eq!(project.worktrees.len(), 1);
        assert!(
            project.worktrees[0].scripts.is_empty(),
            "no fog.json -> empty scripts"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_build_launch_targets_groups_by_common_dir() {
        // `ui/` and `admin/` are worktrees of the same repo -> they collapse to
        // one project named after the repo; a non-git root stays standalone.
        let base = std::env::temp_dir().join(format!("fog-grp-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&base);
        let ui = base.join("ui");
        let admin = base.join("admin");
        let neo = base.join("neo-backend");
        std::fs::create_dir_all(&ui).unwrap();
        std::fs::create_dir_all(&admin).unwrap();
        std::fs::create_dir_all(&neo).unwrap();

        let roots = vec![ui.clone(), admin.clone(), neo.clone()];
        let ui_ref = ui.clone();
        let admin_ref = admin.clone();
        let targets = build_launch_targets(&roots, move |root: &std::path::Path| {
            if root == ui_ref.as_path() || root == admin_ref.as_path() {
                Some("/repo/red-fox/.git".to_string())
            } else {
                None
            }
        });

        assert_eq!(
            targets.projects.len(),
            2,
            "same-repo roots must collapse to one project"
        );
        // Sorted by name: neo-backend < red-fox.
        assert_eq!(targets.projects[0].name, "neo-backend");
        assert_eq!(targets.projects[1].name, "red-fox");
        // The git group is a single project (not a real git repo here, so a
        // single-worktree fallback) covering both roots' identity.
        let rf = &targets.projects[1];
        assert_eq!(rf.worktrees.len(), 1);
        assert_eq!(rf.worktrees[0].path, ui.to_string_lossy());
        // Non-git root keeps its own basename project.
        let neo_p = &targets.projects[0];
        assert_eq!(neo_p.worktrees.len(), 1);
        assert_eq!(neo_p.worktrees[0].path, neo.to_string_lossy());
        assert_eq!(neo_p.worktrees[0].branch, None);

        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn test_reachable_entries_traefik_tls_router() {
        // A Traefik router with a Host rule + TLS + loadbalancer port yields a
        // proper https entry (the /api/services url fix).
        let l = labels(&[
            ("traefik.http.routers.ui.rule", "Host(`ui.red-fox`)"),
            ("traefik.http.routers.ui.tls", "true"),
            ("traefik.http.services.ui.loadbalancer.server.port", "5173"),
        ]);
        let entries = reachable_entries_from(
            &l,
            "redfox-ui-frontend-1",
            "red-fox".into(),
            "ui".into(),
            false,
            "frontend".into(),
            vec![],
            None,
        );
        assert_eq!(entries.len(), 1);
        let e = &entries[0];
        assert_eq!(e.hostname, "ui.red-fox");
        assert_eq!(e.port, "5173");
        assert!(e.tls);
        assert_eq!(e.service, "frontend");
        assert_eq!(entry_url(e), "https://ui.red-fox/");
    }

    #[test]
    fn test_reachable_entries_raw_expose() {
        // `fog.expose` without Traefik yields a raw hostname + host-port entry.
        let l = labels(&[("fog.expose", "true"), ("fog.hostname", "postgres.red-fox")]);
        let entries = reachable_entries_from(
            &l,
            "redfox-postgres-1",
            "red-fox".into(),
            "shared".into(),
            true,
            "postgres".into(),
            vec![],
            Some("55274".into()),
        );
        assert_eq!(entries.len(), 1);
        let e = &entries[0];
        assert_eq!(e.hostname, "postgres.red-fox");
        assert!(e.port.is_empty());
        assert_eq!(e.raw_port.as_deref(), Some("55274"));
        assert!(!e.tls);
        assert_eq!(entry_url(e), "http://postgres.red-fox:55274/");
    }

    #[test]
    fn test_reachable_entries_neither_empty() {
        // A container with no Traefik router and no fog.expose has no reachable
        // entries; the caller falls back to a label-only entry.
        let l = labels(&[("com.docker.compose.service", "api")]);
        let entries = reachable_entries_from(
            &l,
            "redfox-api-1",
            "red-fox".into(),
            "main".into(),
            false,
            "api".into(),
            vec![],
            None,
        );
        assert!(entries.is_empty());
    }

    #[tokio::test]
    async fn test_launch_validation_errors() {
        // Missing both fields -> 400.
        let resp = handle_launch_request(&hyper::Method::POST, b"{}").await;
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
        assert!(String::from_utf8_lossy(&body_bytes(resp).await).contains("config_dir and script"));

        // Missing script -> 400.
        let resp = handle_launch_request(&hyper::Method::POST, br#"{"config_dir":"/tmp"}"#).await;
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
        assert!(String::from_utf8_lossy(&body_bytes(resp).await).contains("config_dir and script"));

        // Unparseable body -> 400.
        let resp = handle_launch_request(&hyper::Method::POST, b"not json").await;
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);

        // Nonexistent config dir -> 400 config directory not found.
        let resp = handle_launch_request(
            &hyper::Method::POST,
            br#"{"config_dir":"/nonexistent/zz/does-not-exist","script":"dev"}"#,
        )
        .await;
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
        assert!(
            String::from_utf8_lossy(&body_bytes(resp).await).contains("config directory not found")
        );

        // A real config dir but with an unknown script -> 400 unknown script.
        let dir = test_dir("unknown-script");
        std::fs::write(dir.join("fog.json"), r#"{"scripts":{"dev":{}}}"#).unwrap();
        let body = serde_json::json!({
            "config_dir": dir.to_string_lossy(),
            "script": "prod",
        });
        let resp =
            handle_launch_request(&hyper::Method::POST, &serde_json::to_vec(&body).unwrap()).await;
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
        assert!(String::from_utf8_lossy(&body_bytes(resp).await).contains("unknown script 'prod'"));
        let _ = std::fs::remove_dir_all(&dir);

        // A real config dir with a requested branch that is not checked out ->
        // 400 no worktree on branch.
        let dir = test_dir("unknown-branch");
        std::fs::write(dir.join("fog.json"), r#"{"scripts":{"dev":{}}}"#).unwrap();
        let body = serde_json::json!({
            "config_dir": dir.to_string_lossy(),
            "script": "dev",
            "branch": "feature-nope",
        });
        let resp =
            handle_launch_request(&hyper::Method::POST, &serde_json::to_vec(&body).unwrap()).await;
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
        assert!(
            String::from_utf8_lossy(&body_bytes(resp).await)
                .contains("no worktree is checked out on branch 'feature-nope'")
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[tokio::test]
    async fn test_launch_dispatch_methods() {
        // GET /api/launch/targets -> 200.
        let resp = api_launch_targets_method(&hyper::Method::GET);
        assert_eq!(resp.status(), StatusCode::OK);

        // POST to /api/launch/targets -> 404 (GET only).
        let resp = api_launch_targets_method(&hyper::Method::POST);
        assert_eq!(resp.status(), StatusCode::NOT_FOUND);

        // GET to /api/launch -> 404 (POST only).
        let resp = handle_launch_request(&hyper::Method::GET, b"{}").await;
        assert_eq!(resp.status(), StatusCode::NOT_FOUND);
    }
}
