//! Build-time embedding of the frontend SPA (built by Vite into `ui/dist/`).
//!
//! The frontend is produced by a parallel worker and may not exist yet when this
//! crate is compiled. Because `rust-embed` / `include_dir!` panic at compile
//! time if the target directory is missing, we instead generate a Rust module at
//! build time:
//!
//!   - If `ui/dist/` exists, every file is copied into `$OUT_DIR/fog_assets/`
//!     and the generated module returns each file's bytes keyed by its URL path
//!     (with `index.html` also served at `/`).
//!   - If `ui/dist/` is absent, try to fetch the prebuilt SPA from the GitHub
//!     Release for `CARGO_PKG_VERSION` (so `cargo install --git` just works
//!     without Node). If that fails (offline, no release yet), embed a minimal
//!     fallback HTML so `/` returns 200 instead of `{"error":"page not found"}`.
//!
//! The generated module is pulled into `src/index.rs` via
//! `include!(concat!(env!("OUT_DIR"), "/fog_embedded.rs"))`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let ui_dist = manifest_dir.join("ui").join("dist");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    // Rebuild when the frontend output changes.
    println!("cargo:rerun-if-changed=ui/dist");
    println!("cargo:rerun-if-changed=ui");
    println!("cargo:rerun-if-env-changed=FOG_SKIP_SPA_DOWNLOAD");
    println!("cargo:rerun-if-env-changed=FOG_REQUIRE_SPA");
    println!("cargo:rerun-if-env-changed=CARGO_NET_OFFLINE");

    // Fast path: local build present.
    if ui_dist.is_dir() {
        generate_from_dir(&ui_dist, &out_dir);
        return;
    }

    // Try to fetch prebuilt SPA from GitHub Release (for `cargo install --git`).
    // Skipped when offline or explicitly disabled.
    if env::var("FOG_SKIP_SPA_DOWNLOAD").is_ok() || env::var("CARGO_NET_OFFLINE").is_ok() {
        if env::var("FOG_REQUIRE_SPA").is_ok() {
            panic!(
                "ui/dist not found and SPA download skipped (FOG_SKIP_SPA_DOWNLOAD/CARGO_NET_OFFLINE set) but FOG_REQUIRE_SPA=1 — refusing to embed fallback"
            );
        }
        println!(
            "cargo:warning=ui/dist not found and SPA download skipped (FOG_SKIP_SPA_DOWNLOAD/CARGO_NET_OFFLINE set); embedding fallback page"
        );
        generate_fallback(&out_dir, &manifest_dir);
        return;
    }

    if let Some(fetched_dist) = try_fetch_spa(&out_dir) {
        // fetched_dist points at a directory containing index.html etc.
        generate_from_dir(&fetched_dist, &out_dir);
        println!("cargo:warning=fetched prebuilt SPA from GitHub Release");
        return;
    }

    if env::var("FOG_REQUIRE_SPA").is_ok() {
        panic!(
            "ui/dist not found and SPA fetch failed (tried v{} + latest) but FOG_REQUIRE_SPA=1 — run `cd ui && pnpm install && pnpm build` or ensure GitHub Release has fog-spa tarball",
            env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "unknown".to_string())
        );
    }
    println!(
        "cargo:warning=ui/dist not found and SPA fetch failed; embedding fallback page (run `cd ui && pnpm install && pnpm build` to embed full SPA)"
    );
    generate_fallback(&out_dir, &manifest_dir);
}

fn generate_from_dir(ui_dist: &Path, out_dir: &Path) {
    let assets_dir = out_dir.join("fog_assets");
    let _ = fs::remove_dir_all(&assets_dir);
    fs::create_dir_all(&assets_dir).expect("create fog_assets dir");

    let mut arms: Vec<String> = Vec::new();
    collect_assets(ui_dist, "", &assets_dir, &mut arms);

    let mut content = String::new();
    content.push_str(
        "// Generated by build.rs — embeds the frontend build from ui/dist.\n\
 // Each arm carries the correct content-type computed from the *real* asset\n\
 // filename (via `mime_for`), never from the request path. This matters for\n\
 // the root alias `/` (which maps to `index.html`): computing the mime from\n\
 // the request path `/` would yield `application/octet-stream` and make the\n\
 // browser download the page instead of rendering it.\n\
 pub fn embedded_get(path: &str) -> Option<(&'static [u8], &'static str)> {\n    let (data, mime) = match path {\n",
    );
    for arm in &arms {
        content.push_str(arm);
        content.push('\n');
    }
    content.push_str("        _ => return None,\n    };\n    Some((data, mime))\n}\n");

    fs::write(out_dir.join("fog_embedded.rs"), content).expect("write fog_embedded.rs");
}

fn generate_fallback(out_dir: &Path, manifest_dir: &Path) {
    let fallback_src = manifest_dir.join("src").join("fallback.html");
    let fallback_bytes =
        fs::read(&fallback_src).unwrap_or_else(|_| b"<h1>fog UI not built</h1>".to_vec());
    let fallback_html_path = out_dir.join("fallback.html");
    fs::write(&fallback_html_path, &fallback_bytes).expect("write fallback.html");

    // Embed fallback for "/" and "/index.html" so serve_spa_fallback returns 200.
    // Use mime_for("index.html") so Content-Type is text/html.
    let content = r#"// Generated by build.rs — fallback when ui/dist absent.
pub fn embedded_get(path: &str) -> Option<(&'static [u8], &'static str)> {
    const FALLBACK: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/fallback.html"));
    match path {
        "/" | "/index.html" => Some((FALLBACK, mime_for("index.html"))),
        _ => None,
    }
}
"#;
    fs::write(out_dir.join("fog_embedded.rs"), content).expect("write fog_embedded.rs");
}

/// Try to fetch `fog-spa-v{version}.tar.gz` from GitHub Releases.
/// Returns Some(path_to_dist_dir) on success.
fn try_fetch_spa(out_dir: &Path) -> Option<PathBuf> {
    let version = env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.1.0".to_string());
    let url = format!(
        "https://github.com/Naputt1/fog/releases/download/v{version}/fog-spa-v{version}.tar.gz"
    );

    // Also try latest release as fallback for `cargo install --git` on main tip
    // where CARGO_PKG_VERSION may not yet have a release.
    let urls = [
        url,
        "https://github.com/Naputt1/fog/releases/latest/download/fog-spa.tar.gz".to_string(),
    ];

    // Cache dir: $CARGO_HOME/.cache/fog or $OUT_DIR fallback
    let cache_dir = env::var("CARGO_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| out_dir.to_path_buf())
        .join("cache")
        .join("fog");
    let _ = fs::create_dir_all(&cache_dir);

    for url in &urls {
        let tar_path = out_dir.join("fog-spa.tar.gz");
        let fetched = fetch_url(url, &tar_path);
        if fetched {
            if let Some(dist) = extract_tar(&tar_path, out_dir) {
                return Some(dist);
            }
            println!("cargo:warning=SPA tarball fetched from {url} but extraction failed");
        } else {
            println!("cargo:warning=SPA fetch failed for {url} (curl/wget missing or 404)");
        }
    }
    None
}

fn fetch_url(url: &str, dest: &Path) -> bool {
    // Prefer curl, fall back to wget. Both are common in CI/containers.
    for (prog, args) in [("curl", vec!["-fsSL", url, "-o"]), ("wget", vec!["-qO"])] {
        let mut cmd = Command::new(prog);
        if prog == "curl" {
            // args = ["-fsSL", url, "-o"] -> curl -fsSL <url> -o <dest>
            cmd.args([args[0], args[1], args[2]]).arg(dest);
        } else {
            cmd.args([args[0]]).arg(dest).arg(url);
        }
        cmd.stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null());
        if let Ok(status) = cmd.status()
            && status.success()
            && dest.exists()
            && fs::metadata(dest).map(|m| m.len() > 0).unwrap_or(false)
        {
            return true;
        }
    }
    false
}

fn extract_tar(tar_path: &Path, out_dir: &Path) -> Option<PathBuf> {
    let extract_dir = out_dir.join("fog-spa-extract");
    let _ = fs::remove_dir_all(&extract_dir);
    let _ = fs::create_dir_all(&extract_dir);

    // tar xzf <file> -C <dir>
    let status = Command::new("tar")
        .args(["xzf"])
        .arg(tar_path)
        .args(["-C"])
        .arg(&extract_dir)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status();

    if status.map(|s| s.success()).unwrap_or(false) {
        // Release tarball is `tar czf fog-spa-vX.tar.gz -C ui dist`
        // so extraction yields `<extract_dir>/dist`
        let candidates = [
            extract_dir.join("dist"),
            extract_dir.join("ui").join("dist"),
            extract_dir.clone(),
        ];
        for cand in &candidates {
            if cand.join("index.html").exists() {
                return Some(cand.clone());
            }
        }
        // Search one level deep for index.html
        if let Ok(entries) = fs::read_dir(&extract_dir) {
            for e in entries.flatten() {
                let p = e.path();
                if p.join("index.html").exists() {
                    return Some(p);
                }
            }
        }
    }
    None
}

/// Recursively walks `dir`, copying each file into `assets_dir` and emitting a
/// match arm mapping its URL path to its embedded bytes.
fn collect_assets(dir: &Path, prefix: &str, assets_dir: &Path, arms: &mut Vec<String>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    let mut entries: Vec<_> = entries.flatten().collect();
    entries.sort_by_key(|e| e.file_name());
    for entry in entries {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        let rel = if prefix.is_empty() {
            name.clone()
        } else {
            format!("{prefix}/{name}")
        };
        if path.is_dir() {
            collect_assets(&path, &rel, assets_dir, arms);
            continue;
        }
        let encoded = rel.replace('/', "__");
        if fs::copy(&path, assets_dir.join(&encoded)).is_err() {
            continue;
        }
        let include =
            format!("include_bytes!(concat!(env!(\"OUT_DIR\"), \"/fog_assets/\", \"{encoded}\"))");
        let url_path = format!("/{rel}");
        // Coerce each arm's `&[u8; N]` to `&[u8]` so all match arms share one
        // type (include_bytes! yields a distinct array size per file, which
        // would otherwise be a compile error). The mime is derived from the
        // real filename (`rel`), so the root alias below maps to `index.html`'s
        // text/html rather than the request path's octet-stream.
        arms.push(format!(
            "        {url_path:?} => ({include} as &[u8], mime_for({rel:?})),"
        ));
        // Serve `index.html` at the root too (SPA entry point).
        if rel == "index.html" {
            arms.push(format!(
                "        \"/\" => ({include} as &[u8], mime_for(\"index.html\")),"
            ));
        }
    }
}
