//! Build-time embedding of the frontend SPA (built by Vite into `ui/dist/`).
//!
//! The frontend is produced by a parallel worker and may not exist yet when this
//! crate is compiled. Because `rust-embed` / `include_dir!` panic at compile
//! time if the target directory is missing, we instead generate a Rust module at
//! build time:
//!
//!   - If `ui/dist/` exists, every file is copied into `$OUT_DIR/fog_assets/`
//!     and the generated module returns each file's bytes keyed by its URL path
//!     (with `index.html` also served at `/`).
//!   - If `ui/dist/` is absent, an empty module is emitted so `cargo build`,
//!     `cargo clippy -D warnings` and `cargo test` all still succeed. The server
//!     then falls back to its generated service-directory page.
//!
//! The generated module is pulled into `src/index.rs` via
//! `include!(concat!(env!("OUT_DIR"), "/fog_embedded.rs"))`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let ui_dist = manifest_dir.join("ui").join("dist");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    // Rebuild when the frontend output changes.
    println!("cargo:rerun-if-changed=ui/dist");
    println!("cargo:rerun-if-changed=ui");

    if !ui_dist.is_dir() {
        let empty = "// Generated by build.rs — ui/dist not present at build time.\n\
pub fn embedded_get(_path: &str) -> Option<(&'static [u8], &'static str)> {\n    None\n}\n";
        fs::write(out_dir.join("fog_embedded.rs"), empty).expect("write fog_embedded.rs");
        return;
    }

    let assets_dir = out_dir.join("fog_assets");
    fs::create_dir_all(&assets_dir).expect("create fog_assets dir");

    let mut arms: Vec<String> = Vec::new();
    collect_assets(&ui_dist, "", &assets_dir, &mut arms);

    let mut content = String::new();
    content.push_str(
        "// Generated by build.rs — embeds the frontend build from ui/dist.\n\
// Each arm carries the correct content-type computed from the *real* asset\n\
// filename (via `mime_for`), never from the request path. This matters for\n\
// the root alias `/` (which maps to `index.html`): computing the mime from\n\
// the request path `/` would yield `application/octet-stream` and make the\n\
// browser download the page instead of rendering it.\n\
pub fn embedded_get(path: &str) -> Option<(&'static [u8], &'static str)> {\n    let (data, mime) = match path {\n",
    );
    for arm in &arms {
        content.push_str(arm);
        content.push('\n');
    }
    content.push_str("        _ => return None,\n    };\n    Some((data, mime))\n}\n");

    fs::write(out_dir.join("fog_embedded.rs"), content).expect("write fog_embedded.rs");
}

/// Recursively walks `dir`, copying each file into `assets_dir` and emitting a
/// match arm mapping its URL path to its embedded bytes.
fn collect_assets(dir: &Path, prefix: &str, assets_dir: &Path, arms: &mut Vec<String>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    let mut entries: Vec<_> = entries.flatten().collect();
    entries.sort_by_key(|e| e.file_name());
    for entry in entries {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        let rel = if prefix.is_empty() {
            name.clone()
        } else {
            format!("{prefix}/{name}")
        };
        if path.is_dir() {
            collect_assets(&path, &rel, assets_dir, arms);
            continue;
        }
        let encoded = rel.replace('/', "__");
        if fs::copy(&path, assets_dir.join(&encoded)).is_err() {
            continue;
        }
        let include =
            format!("include_bytes!(concat!(env!(\"OUT_DIR\"), \"/fog_assets/\", \"{encoded}\"))");
        let url_path = format!("/{rel}");
        // Coerce each arm's `&[u8; N]` to `&[u8]` so all match arms share one
        // type (include_bytes! yields a distinct array size per file, which
        // would otherwise be a compile error). The mime is derived from the
        // real filename (`rel`), so the root alias below maps to `index.html`'s
        // text/html rather than the request path's octet-stream.
        arms.push(format!(
            "        {url_path:?} => ({include} as &[u8], mime_for({rel:?})),"
        ));
        // Serve `index.html` at the root too (SPA entry point).
        if rel == "index.html" {
            arms.push(format!(
                "        \"/\" => ({include} as &[u8], mime_for(\"index.html\")),"
            ));
        }
    }
}
