/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ProjectsProjectRouteImport } from './routes/projects.$project'
import { Route as ProjectsProjectIndexRouteImport } from './routes/projects.$project.index'
import { Route as ProjectsProjectBranchRouteImport } from './routes/projects.$project.$branch'
import { Route as ProjectsProjectBranchIndexRouteImport } from './routes/projects.$project.$branch.index'
import { Route as ProjectsProjectBranchScriptRouteImport } from './routes/projects.$project.$branch.$script'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectRoute = ProjectsProjectRouteImport.update({
  id: '/projects/$project',
  path: '/projects/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIndexRoute = ProjectsProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectRoute,
} as any)
const ProjectsProjectBranchRoute = ProjectsProjectBranchRouteImport.update({
  id: '/$branch',
  path: '/$branch',
  getParentRoute: () => ProjectsProjectRoute,
} as any)
const ProjectsProjectBranchIndexRoute =
  ProjectsProjectBranchIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectBranchRoute,
  } as any)
const ProjectsProjectBranchScriptRoute =
  ProjectsProjectBranchScriptRouteImport.update({
    id: '/$script',
    path: '/$script',
    getParentRoute: () => ProjectsProjectBranchRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/status': typeof StatusRoute
  '/projects/$project': typeof ProjectsProjectRouteWithChildren
  '/projects/$project/$branch': typeof ProjectsProjectBranchRouteWithChildren
  '/projects/$project/': typeof ProjectsProjectIndexRoute
  '/projects/$project/$branch/$script': typeof ProjectsProjectBranchScriptRoute
  '/projects/$project/$branch/': typeof ProjectsProjectBranchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/status': typeof StatusRoute
  '/projects/$project': typeof ProjectsProjectIndexRoute
  '/projects/$project/$branch/$script': typeof ProjectsProjectBranchScriptRoute
  '/projects/$project/$branch': typeof ProjectsProjectBranchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/status': typeof StatusRoute
  '/projects/$project': typeof ProjectsProjectRouteWithChildren
  '/projects/$project/$branch': typeof ProjectsProjectBranchRouteWithChildren
  '/projects/$project/': typeof ProjectsProjectIndexRoute
  '/projects/$project/$branch/$script': typeof ProjectsProjectBranchScriptRoute
  '/projects/$project/$branch/': typeof ProjectsProjectBranchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/logs'
    | '/status'
    | '/projects/$project'
    | '/projects/$project/$branch'
    | '/projects/$project/'
    | '/projects/$project/$branch/$script'
    | '/projects/$project/$branch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/logs'
    | '/status'
    | '/projects/$project'
    | '/projects/$project/$branch/$script'
    | '/projects/$project/$branch'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/logs'
    | '/status'
    | '/projects/$project'
    | '/projects/$project/$branch'
    | '/projects/$project/'
    | '/projects/$project/$branch/$script'
    | '/projects/$project/$branch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  LogsRoute: typeof LogsRoute
  StatusRoute: typeof StatusRoute
  ProjectsProjectRoute: typeof ProjectsProjectRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project': {
      id: '/projects/$project'
      path: '/projects/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof ProjectsProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/': {
      id: '/projects/$project/'
      path: '/'
      fullPath: '/projects/$project/'
      preLoaderRoute: typeof ProjectsProjectIndexRouteImport
      parentRoute: typeof ProjectsProjectRoute
    }
    '/projects/$project/$branch': {
      id: '/projects/$project/$branch'
      path: '/$branch'
      fullPath: '/projects/$project/$branch'
      preLoaderRoute: typeof ProjectsProjectBranchRouteImport
      parentRoute: typeof ProjectsProjectRoute
    }
    '/projects/$project/$branch/': {
      id: '/projects/$project/$branch/'
      path: '/'
      fullPath: '/projects/$project/$branch/'
      preLoaderRoute: typeof ProjectsProjectBranchIndexRouteImport
      parentRoute: typeof ProjectsProjectBranchRoute
    }
    '/projects/$project/$branch/$script': {
      id: '/projects/$project/$branch/$script'
      path: '/$script'
      fullPath: '/projects/$project/$branch/$script'
      preLoaderRoute: typeof ProjectsProjectBranchScriptRouteImport
      parentRoute: typeof ProjectsProjectBranchRoute
    }
  }
}

interface ProjectsProjectBranchRouteChildren {
  ProjectsProjectBranchScriptRoute: typeof ProjectsProjectBranchScriptRoute
  ProjectsProjectBranchIndexRoute: typeof ProjectsProjectBranchIndexRoute
}

const ProjectsProjectBranchRouteChildren: ProjectsProjectBranchRouteChildren = {
  ProjectsProjectBranchScriptRoute: ProjectsProjectBranchScriptRoute,
  ProjectsProjectBranchIndexRoute: ProjectsProjectBranchIndexRoute,
}

const ProjectsProjectBranchRouteWithChildren =
  ProjectsProjectBranchRoute._addFileChildren(
    ProjectsProjectBranchRouteChildren,
  )

interface ProjectsProjectRouteChildren {
  ProjectsProjectBranchRoute: typeof ProjectsProjectBranchRouteWithChildren
  ProjectsProjectIndexRoute: typeof ProjectsProjectIndexRoute
}

const ProjectsProjectRouteChildren: ProjectsProjectRouteChildren = {
  ProjectsProjectBranchRoute: ProjectsProjectBranchRouteWithChildren,
  ProjectsProjectIndexRoute: ProjectsProjectIndexRoute,
}

const ProjectsProjectRouteWithChildren = ProjectsProjectRoute._addFileChildren(
  ProjectsProjectRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  LogsRoute: LogsRoute,
  StatusRoute: StatusRoute,
  ProjectsProjectRoute: ProjectsProjectRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
